name: pks_sem5_p8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  sqflite: ^2.4.0
  path: ^1.9.0
  flutter_slidable: ^3.1.1
  http: ^1.2.2
  supabase_flutter: ^2.8.0
  dropdown_flutter: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
